server:
  port: 9010
spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s


  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      gateway:
        enabled: true
    info:
      env:
        enabled: true
    metrics:
      tags:
        application: ${spring.application.name}



eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8071/eureka"


info:
  app:
    name: "gatewayserver"
    description: "Bank Accounts Application"
    version: "1.0.0"


